### ISSUE TITLE
Notes under games

### ISSUE THREAD

**Issue by Cheyans** [micheljung/downlords-faf-client#136]
http://forums.faforever.com/forums/viewtopic.php?f=42&t=11241#p115335

**Comment by micheljung** [comment]
I'm not exactly sure how it was meant, can we sort out if it's something client-side or for the game-lobby and how exactly it would work?

If it's for the game-lobby, this suggestion should be posted in https://github.com/FAForever/fa instead.

**Comment by Cheyans** [comment]
I think he means for when hosting a game you can add a special note for the game tile, I think we can display this when hovering over the game. Adding it to the streaming protocol shouldn't be too hard

**Comment by Cheyans** [comment]
Ok he means in the actual game, i misunderstood
