### ISSUE TITLE
Excessive tab spam when reconnecting and disconnecting

### ISSUE THREAD

**Issue by Cheyans** [micheljung/downlords-faf-client#137]
![image](https://cloud.githubusercontent.com/assets/8811789/11705528/8aab08e6-9ebe-11e5-8ed4-b586de883777.png)

Maybe we should just indicate the active tab or somehow append the contents of the previous session to the new session in the same tab.

**Comment by micheljung** [comment]
oh yes, this is fixed in feature/126-new-proxy :)
