### ISSUE TITLE
Support Windows taskbar progress

### ISSUE THREAD

**Issue by micheljung** [micheljung/downlords-faf-client#164]
Display task progress in windows taskbar using BridJ, demo code:
https://github.com/nativelibs4java/BridJ/blob/master/src/main/demos/TaskbarListDemo.java

**Comment by tatsujb** [comment]
whats this?

Date: Mon, 11 Jan 2016 00:07:31 -0800

**Comment by Cheyans** [comment]
a notification email? Or if you're talking about the actual taskbar progress, I think he's referring to something like this 
![image] (https://windows7professional.files.wordpress.com/2009/12/progress-bar.jpg)

**Comment by tatsujb** [comment]
oh ok I didn't get this one because it wasn't in the usual github format.

Date: Mon, 11 Jan 2016 17:40:14 -0800
