### ISSUE TITLE
Disconnect from everyone

### ISSUE THREAD

**Issue by tatsujb** [micheljung/downlords-faf-client#201]
very sporadic.

happens only on Downlords's client :(
dunno what's causing it. 

disconnection is very sudden and from everyone. internet continues to function
reconnecting to others is impossible.

**Comment by micheljung** [comment]
I know this problem exists but I haven't investigated yet :\
I'm glad for anyone who tests, but I still wouldn't use my client for regular gaming before it reaches Beta :-)

**Comment by tatsujb** [comment]
here

**Comment by tatsujb** [comment]
https://drive.google.com/file/d/0BzN9wSaRvA86VWk0SnlKaTlqSkE/view?usp=sharing is this it?

**Comment by micheljung** [comment]
do you know what date/time the problem occurred?

**Comment by micheljung** [comment]
This was supposedly caused by memory leaks which are fixed now.
