### ISSUE TITLE
Cannot Create or Join Games

### ISSUE THREAD

**Issue by Memhave** [micheljung/downlords-faf-client#206]
Gives a blank error message.
Has "Connectivity: Unknown" (although I can host on normal FAF client).
[Creating](http://puu.sh/ofVA1/fef77335bd.jpg)
[Joining](http://puu.sh/ofVC7/f35af1342c.jpg)

**Comment by micheljung** [comment]
Hi, thanks for reporting and sorry for the late response. Does this still happen? In the newest version, the error details will be displayed.

**Comment by Androish** [comment]
I got this starting from 0.6.8.
Still a problem in 0.6.9
http://i.imgur.com/3VVK6Gu.png

**Comment by micheljung** [comment]
Would you mind sending me the logs?

**Comment by micheljung** [comment]
Oh and, sorry, I fixed the detail message but I didn't merge it into the release x)

**Comment by Androish** [comment]
Still need logs?

**Comment by micheljung** [comment]
Sorry it got closed as I pushed the detail fix.
Yes please

**Comment by Androish** [comment]
[downlords-faf-client.zip](https://github.com/micheljung/downlords-faf-client/files/258060/downlords-faf-client.zip)

**Comment by micheljung** [comment]
According to the log, your routers IP address is 192.168.1.2, however your computer's IP address is detected as 25.136.203.37 (This is achieved by retrieving the name of the host from the system, then resolving that name into an IP address)

Do you have any Idea why that could be, and if that's your public IP?

**Comment by Androish** [comment]
http://whatismyipaddress.com/ip/25.136.203.37

UK Ministry of Defence lol.

Only thing I can think of that is anything out of the ordinary is that I have Private Internet Access(vpn) installed. But not running. That is not my external IP no. Neither is it a VPN IP.

**Comment by micheljung** [comment]
Would you mind letting me have a look at it?

**Comment by Androish** [comment]
Sure

**Comment by Memhave** [comment]
I'll reinstall the client and see if I can get logs when I get home, later tonight.

**Comment by Androish** [comment]
Just pop on faf and we can figure out the details there

**Comment by micheljung** [comment]
Alright we have a workaround: Disabled other Network adapters like Hamachi or VirtualBox, meanwhile I'll figure out how I can detect the "correct" interface to use :)
