### ISSUE TITLE
Search chat users bugged

### ISSUE THREAD

**Issue by Androish** [micheljung/downlords-faf-client#214]
Searching for a user removes everyone that does not meet the search kriteria.

But after a while it fills up with users that have far different names. My theory is that any new users that join the lobby show up.
![search](https://cloud.githubusercontent.com/assets/16946169/15224449/af18b158-1879-11e6-931c-50360d504d23.PNG)

**Comment by micheljung** [comment]
Blame Aulex, thanks for reporting though :-)
Duplicates #183

**Comment by Androish** [comment]
Ahh I did not look hard enough for duplicate ^^

**Comment by micheljung** [comment]
No problem, just keep reporting :)

**Comment by Cheyans** [comment]
Heh, if I ever find time in my life again I'll start fixing alot of shit
