### ISSUE TITLE
Implement "ladder notification"

### ISSUE THREAD

**Issue by micheljung** [micheljung/downlords-faf-client#22]
Notify the user when another player in his range is searching for a 1v1 ranked game opponent.

This is already implemented, however ugly in the status bar. Think of some better way to notify the user. One idea:

Display a transient notification that, when the user clicks on it, opens the ranked1v1 screen.

Don't display while the user is playing a game

**Comment by tatsujb** [comment]
I'm tacking this!

**Comment by Farmsletje** [comment]
Seems like this very important feature was never implemented?

**Comment by Sheikah45** [comment]
I believe this actually resulted in the current toast we have now
