### ISSUE TITLE
Redundant notifications

### ISSUE THREAD

**Issue by Cheyans** [micheljung/downlords-faf-client#40]
Issue: Redundant notifications appear as seen here 
http://i.imgur.com/xt3Y6eU.jpg
Reproduce:
Have port check already fail, then click retry

**Comment by micheljung** [comment]
Thank you for testing and reporting!
On your screenshot I see that the notification Icons do not work for you. How did you run the client? Do you have src/main/resources/font/fontawesome-webfont.ttf?

**Comment by Cheyans** [comment]
Once I get home tonight I'll be able to tell you, I set it up with tatsu, he noticed the issue too.
