### ISSUE TITLE
Many users have requested clicking on the map preview in find games make it even bigger.

### ISSUE THREAD

**Issue by tatsujb** [micheljung/downlords-faf-client#51]
I see that as a valid request.

**Comment by micheljung** [comment]
Well then do something useful instead of a useless navigation animation nobody requests ;)

**Comment by micheljung** [comment]
They want to be able to click on the *large* preview in order to display it even larger. I don't know if we can generate a larger preview or if we have to upscale the one we have.

**Comment by Cheyans** [comment]
Implemented for the most part, needs to be made prettier and waiting for api support to properly fetch the map info

**Comment by Cheyans** [comment]
#79
