### ISSUE TITLE
the notification for FA.exe not found comes back even after it's been set and games have been played.

### ISSUE THREAD

**Issue by tatsujb** [micheljung/downlords-faf-client#53]
saw this on another PC. win7 

this means that create game stays grayed out as well even though he can join and play games.

this persists even if you re-specify the location of FA.

**Comment by micheljung** [comment]
I need log output in order to verify/analyse this

**Comment by tatsujb** [comment]
here's the log from another player who has the same bug. 
https://drive.google.com/file/d/0BzN9wSaRvA86RUdOUjFudXFuWmM/view?usp=sharing

**Comment by micheljung** [comment]
I experienced that sometimes as well, but not in the last few months. I'll close this for now.
