### ISSUE TITLE
Dirty regions aren't always re-rendered in WebView

### ISSUE THREAD

**Issue by Cheyans** [micheljung/downlords-faf-client#56]
Not sure how this happened but yea, look at the top half of irc chat
![image](https://cloud.githubusercontent.com/assets/8811789/8510198/29a154a6-22a4-11e5-8e71-5e38373abf7d.png)

**Comment by micheljung** [comment]
Sometimes the WebView doesn't update itself properly when you've switched to another tab and then go back. I don't yet know in which circumstances however. That's some "dirty region" problem; if you select all the text it will "fix" the view again as it is re-rendered.
This may get fixed along with https://bugs.openjdk.java.net/browse/JDK-8090547 even though it's not the exact same issue.
