### ISSUE TITLE
Easily see what people are playing

### ISSUE THREAD

**Issue by ModcaFox** [micheljung/downlords-faf-client#57]
Have it so that if you hover over somone's name in aeolus it gives you the info as if you hovered over a game lobby plus the map name.

-ModcaFox

**Comment by Cheyans** [comment]
I suggest implementing the same hover mechanic like this in the friends list 
![image](https://cloud.githubusercontent.com/assets/8811789/8510628/0de840ae-22c1-11e5-9d01-e9f30b9a57d3.png)

**Comment by Cheyans** [comment]
#103
