### ISSUE TITLE
Broken map previews

### ISSUE THREAD

**Issue by ToonShader** [micheljung/downlords-faf-client#58]
When a user hosts a map which is not in the map vault, other FAF users will recieve a blank/broken preview image for that map. When the map is uploaded to the vault, or a map with the same name is uploaded, this preview image is never changed. This results in one of the scenarios which creates users having broken/missing preview images in the find games tab for certain maps..

**Comment by micheljung** [comment]
If a map is not in the map vault, there's nothing we can do but display a fallback image (which we currently do correctly?)
As every fetched map preview is cached for the lifetime of the client (also if there is none), the client needs to be restarted in order for the map preview to be fetched again.

I see this as a very rare edge case.

**Comment by ToonShader** [comment]
The issue mainly occurs when someone making a map tests it through the faf client before uploading. Its actually quite common as most map makers do not attempt to avoid this problem or are unaware of how it occurs. Even some of the most popular maps have had this issue (crimson fued). While it can be worked around by testing a map under a different name its extremely tedious.

While the issue is avoidable, fixing it would greatly improve the experience of new, and even experienced, map makers, as there is already a long list of do's and dont's for making a map work properly.
