### ISSUE TITLE
lobby crash on BenjaminB's PC

### ISSUE THREAD

**Issue by tatsujb** [micheljung/downlords-faf-client#61]
this is a screencap from his PC : 
https://drive.google.com/file/d/0BzN9wSaRvA86Q3RXNU5sa0EycVU/view?usp=sharing

same log file as the notification error but I'm attempting to get the new log file.

**Comment by tatsujb** [comment]
https://drive.google.com/file/d/0BzN9wSaRvA86Sjh1ZTJiYW5VZFU/view?usp=sharing

**Comment by micheljung** [comment]
Did this happen when he was using the client? I only ever experienced this during debugging.
His system clock says 2:47 but the log file runs until 2:52. Just an observation... I have no idea what could cause this. Does it happen repeatedly?

**Comment by tatsujb** [comment]
happened only once. It did happen while he was using it yes. maybe it's a one-off.

**Comment by Cheyans** [comment]
Did he attempt to reproduce the issue

**Comment by tatsujb** [comment]
nah.

**Comment by micheljung** [comment]
Nothing we could reproduce
