### ISSUE TITLE
JDK 8u60

### ISSUE THREAD

**Issue by micheljung** [micheljung/downlords-faf-client#69]
JDK 8u60 [is going to be released in August](http://openjdk.java.net/projects/jdk8u/releases/8u60.html).
2 bugs should be fixed that affected us directly:
* [JDK-8097541: [CSS] NPE in com.sun.javafx.css.StyleManager.findMatchingStyles](https://bugs.openjdk.java.net/browse/JDK-8097541)
* [JDK-8116513: WebView back buffer should initially be transparent rather than solid white](https://bugs.openjdk.java.net/browse/JDK-8116513)

Update to JDK 8u60 and remove workaround code (search code for issue ID).

**Comment by Cheyans** [comment]
How does the first fix help us?

**Comment by micheljung** [comment]
We experience that NPE when creating ChatUserControls in a background thread. I changed it so they are created on the UI thread to avoid this exception; however that's now the reason why the UI lags while initially loading all ~600 chat users. With that bug fixed we can change it back and the application will run without that lag.

**Comment by micheljung** [comment]
JDK 8u60 has been released: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by micheljung** [comment]
Argh...!! https://bitbucket.org/controlsfx/controlsfx/issues/526/comsunjavafxutils-changes-to

**Comment by Cheyans** [comment]
lol "you need to make the changes in the code yourself to make it compilable."

**Comment by micheljung** [comment]
None of both issues is listed in [the list of 8u60 bug fixes](http://www.oracle.com/technetwork/java/javase/2col/8u60-bugfixes-2620228.html).

However, the issue we had because of JDK-8097541 does no longer seem to appear.
The webview is still not transparent however.
