### ISSUE TITLE
Click on name in chat should open private message tab

### ISSUE THREAD

**Issue by Cheyans** [micheljung/downlords-faf-client#92]
http://forums.faforever.com/forums/viewtopic.php?f=42&t=10717&p=108997#p108997

**Comment by Cheyans** [comment]
7a1f48fcbfaace443aba72969762017bab557ee3 added

**Comment by micheljung** [comment]
Not yet in master, pushing back

**Comment by Cheyans** [comment]
now single click

**Comment by Cheyans** [comment]
#103
