### ISSUE TITLE
Show some content when all chat tabs were closed

### ISSUE THREAD

**Issue by micheljung** [micheljung/downlords-faf-client#98]
Similar to Intellij's editor
![image](https://cloud.githubusercontent.com/assets/1864183/9743001/347e3f6c-5664-11e5-816e-54c550db2dfc.png)

Allow the user to join channels.

**Comment by Cheyans** [comment]
Show the most up to date announcement, ongoing tournaments, and maybe some tips and tricks

**Comment by micheljung** [comment]
I don't think it's the right place for these things. This is meant for when a user closed all tabs, he shouldn't see just an empty screen but also he shouldn't see much content. Just something to re-join a channel or some information.

I not put a join-channel field there.
